# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
# relative_permalinks: true

# Setup
title:               'and so on'
tagline:             'avid reader, occasional programmer, chronic blogger'
description:         'thanks for the theme @mbo'
url:                
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              zhengyang choong
  url:               https://twitter.com/mdo
  email:             zhengyangchoong40@gmail.com

# Custom vars
version:             1.0.0
