# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
# relative_permalinks: true

# Setup
title:               'and so on'
tagline:             'musings from the other side'
description:         'theme from @mbo'
url:                 ''
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              zhengyang choong
  url:               ''
  email:             zhengyangchoong40@gmail.com

# Custom vars
version:             1.0.0
